// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIkRerla0cxi0jueHZF1HdOTHfBmeD8yI',
    appId: '1:952524530744:web:e3178c3e54c1234a11f2cd',
    messagingSenderId: '952524530744',
    projectId: 'moviesapp-a012f',
    authDomain: 'moviesapp-a012f.firebaseapp.com',
    storageBucket: 'moviesapp-a012f.firebasestorage.app',
    measurementId: 'G-Q6EM7EVVJY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRtm4-_WerwOMR3gS1qoitSJyl0P7-Z6g',
    appId: '1:952524530744:ios:f86da34ccd58cb6911f2cd',
    messagingSenderId: '952524530744',
    projectId: 'moviesapp-a012f',
    storageBucket: 'moviesapp-a012f.firebasestorage.app',
    iosClientId: '952524530744-vqjoe8jg1u8k022av5vivarpojdusap0.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIkRerla0cxi0jueHZF1HdOTHfBmeD8yI',
    appId: '1:952524530744:web:40888505ca21bb2011f2cd',
    messagingSenderId: '952524530744',
    projectId: 'moviesapp-a012f',
    authDomain: 'moviesapp-a012f.firebaseapp.com',
    storageBucket: 'moviesapp-a012f.firebasestorage.app',
    measurementId: 'G-8YLJYZ72YF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRtm4-_WerwOMR3gS1qoitSJyl0P7-Z6g',
    appId: '1:952524530744:ios:f86da34ccd58cb6911f2cd',
    messagingSenderId: '952524530744',
    projectId: 'moviesapp-a012f',
    storageBucket: 'moviesapp-a012f.firebasestorage.app',
    iosClientId: '952524530744-vqjoe8jg1u8k022av5vivarpojdusap0.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkWz479ja03WBkHi-QSgdaFFsliOBNBV8',
    appId: '1:952524530744:android:91d8b133d4da859c11f2cd',
    messagingSenderId: '952524530744',
    projectId: 'moviesapp-a012f',
    storageBucket: 'moviesapp-a012f.firebasestorage.app',
  );

}